version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ams_frontend_dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules


  db:
    image: postgres:latest
    volumes:
      - ams_data:/var/lib/postgresql/data/
    environment:
      # POSTGRES_DB: ${DB_NAME}
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
    - POSTGRES_DB=amsDB
    - POSTGRES_USER=amsUser
    - POSTGRES_PASSWORD=amsPassword
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ams_backend_dev
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/backend
      - /app/.venv

volumes:
  ams_data:


