

dev-build:
	docker compose -f docker-compose.production.yaml build --no-cache
dev-up:
	docker compose -f docker-compose.production.yaml up
dev-down:
	docker compose -f docker-compose.production.yaml down
dev-db:
	docker-compose -f docker-compose.production.yaml up db
dev-seed:
		python manage.py loaddata seed/*