<template>
  <PageLayout>
    <template #content >
      <div class="sm:ml-[25vw] lg:ml-[15vw] px-8  mt-20 text-slate-300 ">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni cum deleniti earum aliquam. Laudantium deserunt tempore quia! Enim nobis officia cumque culpa minus doloremque, saepe, tempore aspernatur iusto eaque nostrum!
      </div>
        

  </template>
  </PageLayout>
</template>

<script>


</script>